# Azure DevOps pipeline to generate a report of the Pivotal stories completed in the last predefined 
# period of time for all interesting projects. Optionally, the report can also be sent to a Slack 
# channel.
#
# You need to add the following pipeline variables and set them with valid tokens using the Azure
# DevOps portal interface before running: 
# - PIVOTAL_TOKEN: a valid Pivotal token to access the stories in the projects
# - SLACK_TOKEN: if you want to forward a message to Slack
#
# Other configuration settings are defined hard-coded in the Python scripts, for instance:
# - the list of all Pivotal project ids we want to print stories overview
# - the Slack channel (e.g. "#dev_io") 

variables:
  - name: PYTHON_VERSION
    value: '3.8.2'

# We want to run this pipeline by only using scheduled triggers (disable PR and CI triggers)
trigger: none
pr: none

schedules:
  - cron: "0 12 * * 0"
    displayName: Weekly Monday Report
    branches:
      include:
      - master
    always: true

jobs:  
  - job: 'week_stories'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(PYTHON_VERSION)'

      - bash: |
          pip3 install -r ./requirements.txt
        displayName: 'Install dependencies'

      - bash: |
          python3 src/main.py
        env:
          PIVOTAL_TOKEN: '$(PIVOTAL_TOKEN)'
          SLACK_TOKEN: '$(SLACK_TOKEN)'
        displayName: 'Run python script'
