# Azure DevOps pipeline to generate a report of the Pivotal stories completed in the last predefined 
# period of time for all interesting projects. Optionally, the report can also be sent to a Slack 
# channel.
#
# You need to add the following pipeline variables and set them with valid tokens: 
# - PIVOTAL_TOKEN: a valid Pivotal token to access the stories in the projects
# - SLACK_TOKEN: if you want to forward a message to Slack

variables:
  - name: PYTHON_VERSION
    value: '3.7'

jobs:  
  - job: 'week_stories'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(PYTHON_VERSION)'

      - script: |
          pip install -r ./requirements.txt
        displayName: 'Install dependencies'

      - script: |
          python src/main.py
        env:
          PIVOTAL_TOKEN: '$PIVOTAL_TOKEN'
        displayName: 'Run python script'
